In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from collections import Counter
import ipywidgets as widgets
import io

In [2]:
fn = "EsempioTimeSeries.xlsx"

In [3]:
df1 = pd.read_excel(fn,0)
df2 = pd.read_excel(fn,1)

df1 = df1.drop(['Unnamed: 6', 'Unnamed: 7'], axis=1)
df1.columns = ["Cognome", "Nome", "utente", "ComuneProvenienza", "DataInizio","DataFine"]
df2.columns = ["Cognome", "Nome", "utente", "ComuneProvenienza", "DataInizio","DataFine","delibera666", "delibera543","delibera733","Entrate"]

/home/stfz/.local/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [18]:
df =  {}
type(df)
df["sheet0"] = None
df["sheet1"] = None

In [5]:
microstruttura = df1.iloc[1]
microstruttura = microstruttura[1]

ente = df1.iloc[2]
ente = ente[1]
df1.insert(0, "Microstruttura", microstruttura)
df1.insert(0, "Ente", ente)
df1 = df1.drop(labels=range(0, 6), axis=0)
validi = df1["Cognome"].notna()
df1 = df1[validi]

microstruttura = df2.iloc[1]
microstruttura = microstruttura[1]
ente = df2.iloc[2]
ente = ente[1]
df2.insert(0, "Microstruttura", microstruttura)
df2.insert(0, "Ente", ente)
df2 = df2.drop(labels=range(0, 6), axis=0)
validi = df2["Cognome"].notna()
df2 = df2[validi]

In [6]:
df1["DataInizio"] = df1["DataInizio"].astype("datetime64[ns]")
df1["DataFine"] = df1["DataFine"].astype("datetime64[ns]")

In [7]:
condition1 = pd.to_datetime(df2['DataFine'], errors='coerce').isnull()
condition2 = pd.to_datetime(df2['DataInizio'], errors='coerce').isnull()
condition = condition1 | condition2

In [8]:
df2['errData'] = np.nan
df2['errData'] = df2['errData'].astype("boolean")

In [9]:
df1["DataInizio"].astype("datetime64[ns]").dt.year

6     2017
7     2017
8     2018
9     2018
10    2019
Name: DataInizio, dtype: int64

In [10]:
df2.loc[condition, "errData"] = True

In [11]:
c = df2["errData"] == True

In [12]:
df2[c]

Empty DataFrame
Columns: [Ente, Microstruttura, Cognome, Nome, utente, ComuneProvenienza, DataInizio, DataFine, delibera666, delibera543, delibera733, Entrate, errData]
Index: []

In [13]:
df2["DataInizio"] = df2["DataInizio"].astype("datetime64[ns]")
df2["DataFine"] = df2["DataFine"].astype("datetime64[ns]")

In [20]:
df["sheet0"] = df1
df["sheet1"] = df2

In [25]:
df["sheet0"]

,Ente,Microstruttura,Cognome,Nome,utente,ComuneProvenienza,DataInizio,DataFine
6,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Phantom,Fritz,aziendale,NaN,2017-03-01,2020-07-30
7,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Plaseller,Carmen,aziendale,NaN,2017-09-05,2020-07-30
8,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Rigo,Stefan,comunale,Avelengo,2018-11-11,2021-07-30
9,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Fritz,Michi,aziendale,NaN,2018-03-01,2020-06-30
10,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Mini,Max,comunale,Barbiano,2019-05-05,2021-07-30

In [26]:
df["sheet1"]

,Ente,Microstruttura,Cognome,Nome,utente,ComuneProvenienza,DataInizio,DataFine,delibera666,delibera543,delibera733,Entrate,errData
6,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Brunner,Valentina,aziendale,NaN,2020-02-02,2022-08-02,NaN,NaN,NaN,NaN,<NA>
7,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",La Gioia,Isabella,comunale,Laives,2020-02-03,2022-08-02,500,50,0,NaN,<NA>
8,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Naddeo,Leo,aziendale,NaN,2020-03-01,2022-08-02,NaN,NaN,NaN,NaN,<NA>
9,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Pilato,Nicole,comunale,Vadena,2020-03-01,2022-08-02,300,200,0,NaN,<NA>
10,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Pilato,Martin,comunale,Vadena,2020-03-01,2022-08-02,400,100,0,NaN,<NA>
11,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Collatuzzo,Tommaso,comunale,Appiano s.s.d.v.,2020-03-01,2022-08-02,500,100,0,NaN,<NA>
12,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Targa,Matilde,aziendale,NaN,2020-04-02,2022-08-02,NaN,NaN,NaN,NaN,<NA>
13,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Oieni,Giada,comunale,Lana,2020-04-03,2022-08-02,1200,300,0,NaN,<NA>
14,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Innerebner,Mia,aziendale,NaN,2020-06-30,2022-08-02,NaN,NaN,NaN,NaN,<NA>
15,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Turani,Nina,comunale,Vadena,2020-09-01,2022-08-02,800,200,0,NaN,<NA>
16,Cooperativa sociale Coccinella,"Bolzano, Lungo Talvera S. Quirino, 10, Coccine...",Turani,Elias,comunale,Vadena,2020-09-01,2022-08-02,850,200,0,NaN,<NA>